# Site settings
title: callumpember.com
description: "A blog about technology"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://www.callumpember.com"

# User settings
username: Callum Pember
user_title: DevOps Engineer
email: callum@callumpember.com
github_username: callum-p
linkedin_url: "https://linkedin.com/in/callum-pember-ba261660"
disqus_username: callumpember-com
profile_picture: /assets/img/profile.jpg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index

#projects:
#  - name: asciilang
#    url: https://github.com/victorvoid/asciilang
#  - name: vim-frontend
#    url: https://github.com/victorvoid/vim-frontend
#  - name: generator-capybara
#    url: https://github.com/victorvoid/generator-capybara

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
